name: main
on:
  push:
    branches:
      - main
env:
  GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: step Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: install dependencies
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          npm ci

      - name: build docs
        run: npm run build

      - name: build library
        run: npm run build:lib

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: install dependencies
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          npm ci

      - name: run semantic-release
        run: npx semantic-release --debug

  deploy:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: install vercel CLI
        run: npm install --global vercel@latest

      - name: pull vercel environment information
        run: vercel pull --yes --environment=production --token=$VERCEL_TOKEN

      - name: build project artifacts
        run: vercel build --prod --token=$VERCEL_TOKEN

      - name: deploy project artifacts to vercel
        run: vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
